version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: friendconnectdb
      MYSQL_USER: root
      MYSQL_PASSWORD: shilpag20
      MYSQL_ROOT_PASSWORD: shilpag20
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=friendconnectdb
      - DB_USER=root
      - DB_PASSWORD=shilpag20

volumes:
  db_data: